### ISSUE TITLE
"ospf_neighbours_up" returns the following error when attempting to use with vrouter and IP address present on firewall

### ISSUE THREAD

**Issue by smatt241** [gregfoletta/Device-PaloAlto#1]
fileserver@autoTest-virtual-machine:~/auto_test$ prove -v -r
./outputs/t/PA_Candidate_Lab.t .. 
ok 1 - use Device::PaloAlto::Firewall;
ok 2 - PAN-OS version at least at 6.0.0
Mandatory parameter 'neighbours' missing in call to Device::PaloAlto::Firewall::Test::ospf_neighbours_up
at /usr/local/share/perl/5.24.1/Device/PaloAlto/Firewall/Test.pm line 488.
                Device::PaloAlto::Firewall::Test::ospf_neighbours_up(undef) called at ./outputs/t/PA_Candidate_Lab.t line 200
                main::__ANON__("neighbours", ARRAY(0x556be5d9df48), "vrouter", "VR01") called at ./outputs/t/PA_Candidate_Lab.t line 135
                main::__ANON__(HASH(0x556be5dbbea0)) called at ./outputs/t/PA_Candidate_Lab.t line 138
                main::map_test(CODE(0x556be80226d8), HASH(0x556be5dbbea0)) called at ./outputs/t/PA_Candidate_Lab.t line 200
#Tests were run but no plan was declared and done_testing() was not seen.
#Looks like your test exited with 255 just after 2.
Dubious, test returned 255 (wstat 65280, 0xff00)
All 2 subtests passed 

Test Summary Report
-------------------
./outputs/t/PA_Candidate_Lab.t (Wstat: 65280 Tests: 2 Failed: 0)
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
Files=1, Tests=2,  2 wallclock secs ( 0.10 usr  0.00 sys +  1.33 cusr  0.10 csys =  1.53 CPU)
Result: FAIL

**Comment by gregfoletta** [comment]
This was actually an issue in the network-test-templates repo. Commit and fix here: https://github.com/gregfoletta/network-test-templates/commit/a2e7db24bbaaf565a3d83cadf43a1e6bb9c25cd8
